/* Generated By:JavaCC: Do not edit this line. LinguagemConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LinguagemConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETRA = 5;
  /** RegularExpression Id. */
  int NUM = 6;
  /** RegularExpression Id. */
  int PONTOEVIRGULA = 7;
  /** RegularExpression Id. */
  int DOISPONTOS = 8;
  /** RegularExpression Id. */
  int VAR = 9;
  /** RegularExpression Id. */
  int ACHAVES = 10;
  /** RegularExpression Id. */
  int FCHAVES = 11;
  /** RegularExpression Id. */
  int APARENTESES = 12;
  /** RegularExpression Id. */
  int FPARENTESES = 13;
  /** RegularExpression Id. */
  int MAIN = 14;
  /** RegularExpression Id. */
  int PRINT = 15;
  /** RegularExpression Id. */
  int TIPO = 16;
  /** RegularExpression Id. */
  int ID = 17;
  /** RegularExpression Id. */
  int BINOP = 18;
  /** RegularExpression Id. */
  int ATRIB = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<LETRA>",
    "<NUM>",
    "\";\"",
    "\":\"",
    "\"var\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"main\"",
    "\"print\"",
    "\"int\"",
    "<ID>",
    "<BINOP>",
    "\":=\"",
  };

}
